// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1A8wlA0QkYBA_7OUnl1ouT3SbeoAouKk',
    appId: '1:279410526870:web:42b774ee7fc75453a910b7',
    messagingSenderId: '279410526870',
    projectId: 'paya-75f62',
    authDomain: 'paya-75f62.firebaseapp.com',
    databaseURL: 'https://paya-75f62-default-rtdb.firebaseio.com',
    storageBucket: 'paya-75f62.firebasestorage.app',
    measurementId: 'G-SY378MQLRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrdZxgn9_9WIkkUqWrLN2EoMP1P_otdg',
    appId: '1:279410526870:android:b21c45fa18350adca910b7',
    messagingSenderId: '279410526870',
    projectId: 'paya-75f62',
    databaseURL: 'https://paya-75f62-default-rtdb.firebaseio.com',
    storageBucket: 'paya-75f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWsbi3t4I_9472QUgOJQ3RnggkcjMy4M',
    appId: '1:279410526870:ios:38e098a8f69eec07a910b7',
    messagingSenderId: '279410526870',
    projectId: 'paya-75f62',
    databaseURL: 'https://paya-75f62-default-rtdb.firebaseio.com',
    storageBucket: 'paya-75f62.firebasestorage.app',
    iosBundleId: 'com.example.paYa',
  );
}
